version: "3.9" # optional since v1.27.0
name: interactive-map
services:
  nginx_http:
    build: ../nginx/http
    volumes:
      - nginx_http_static:/usr/share/nginx/html:ro
    ports:
      - "80:80"
  certbot:
    depends_on:
      - nginx_http
    image: certbot/certbot
    volumes:
      - nginx_http_static:/var/www/certbot/:rw
      - nginx_https_certificates:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path /var/www/certbot/ -d $DOMAIN --email $DOMAIN_EMAIL --agree-tos --no-eff-email --dry-run

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
  server:
    platform: linux/x86_64
    image: $IMAGE
    environment:
      DB_HOST: postgres
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      DB_PORT: 5432
      HOST: 0.0.0.0
      DB_USERNAME: postgres
      JWT_SECRET: $JWT_SECRET
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      GOOGLE_CALLBACK_URL: $GOOGLE_CALLBACK_URL
    depends_on:
      - postgres
    links:
      - postgres
  nginx_https:
    depends_on:
      - server
    build: ../nginx/https
    environment:
      SERVER_HOST: server
    ports:
      - "443:443"
    links:
      - server

volumes:
  nginx_http_static:
  nginx_https_static:
  nginx_https_certificates:
