version: "3.9" # optional since v1.27.0
name: nginx

services:
  nginx_http:
    image: nginx:latest
    volumes:
      - ~/client:/usr/share/nginx/html:ro
      - ~/nginx/https/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "444:443"
