version: "3.9" # optional since v1.27.0
name: nginx

services:
  nginx_https:
    image: nginx:latest
    volumes:
      - ~/client:/usr/share/nginx/html:ro
      - ~/nginx/https/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/certificates:/etc/letsencrypt:ro
    ports:
      - "443:443"

networks:
  default:
    name: interactive-map_default
    external: true