version: "3.9" # optional since v1.27.0
name: certbot

volumes:
  nginx_http_static:

services:
  nginx_http:
    image: nginx:latest
    volumes:
      - nginx_http_static:/usr/share/nginx/html:ro
      - ~/nginx/http/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  certbot:
    depends_on:
      - nginx_http
    image: certbot/certbot
    volumes:
      - nginx_http_static:/var/www/certbot/:rw
      - ~/certificates:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path /var/www/certbot/ -d $DOMAIN --email $DOMAIN_EMAIL --agree-tos --no-eff-email



