version: "3.9" # optional since v1.27.0
name: certbot

volumes:
  nginx_http_static:
  nginx_https_certificates:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/certificates
  nginx_http_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/nginx/http/nginx.conf

services:
  nginx_http:
    image: nginx:latest
    volumes:
      - nginx_http_static:/usr/share/nginx/html:ro
      - nginx_http_config:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  certbot:
    depends_on:
      - nginx_http
    image: certbot/certbot
    volumes:
      - nginx_http_static:/var/www/certbot/:rw
      - nginx_https_certificates:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path /var/www/certbot/ -d $DOMAIN --email $DOMAIN_EMAIL --agree-tos --no-eff-email --dry-run



