name: Copy files to server

on: workflow_dispatch

jobs:
  copy-to-server:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy compose to server
        uses: appleboy/scp-action@master
        with:
          local: "compose.yml"
          remote: ${{ secrets.COMPOSE_PATH }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
