# This is a basic workflow that is manually triggered
name: Manual workflow

on:
  workflow_dispatch:
    # inputs:
    #   choice:
    #     type: choice
    #     description: 'Restart nginx:'
    #     options:
    #       - http
    #       - https

jobs:
  certbot-compose-to-server:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy compose to server
        uses: appleboy/scp-action@master
        with:
          source: docker/certbot/compose.yml
          target: ~/compose/certbot
          strip_components: 1
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

  copy-nginx-config-to-server:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy compose to server
        uses: appleboy/scp-action@master
        with:
          source: nginx/https/nginx.conf
          target: ~/nginx/https
          strip_components: 1
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
  
  update-certificates:
    needs:
      - copy-nginx-config-to-server
      - certbot-compose-to-server
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - name: Run certbot
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          DOMAIN_EMAIL: ${{ secrets.DOMAIN_EMAIL }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: DOMAIN,DOMAIN_EMAIL
          script: |
            docker compose -f ~/compose/certbot/compose.yml up -d

  # restart-nginx_https:
  #   needs:
  #     - copy-nginx_https-to-server
  #     - copy-compose-to-server
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: production
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run nginx_https job
  #       env:
  #         DOMAIN: ${{ secrets.DOMAIN }}
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         password: ${{ secrets.SSH_PASSWORD }}
  #         envs: DOMAIN
  #         script: |
  #           docker compose -f ~/compose/compose.yml up -d nginx_https
