name: Copy nginx.conf to server

on:
  workflow_dispatch:

jobs:
  copy-nginx_http-to-server:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy compose to server
        uses: appleboy/scp-action@master
        with:
          source: "nginx/http/nginx.conf"
          target: ${{ vars.NGINX_HTTP_PATH }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
  copy-nginx_https-to-server:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy compose to server
        uses: appleboy/scp-action@master
        with:
          source: nginx/https/nginx.conf
          target: ${{ vars.NGINX_HTTPS_PATH }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
